version: 2
executorType: docker
containerInfo:
  - image: kkarczmarczyk/node-yarn:7.4
stages:
  build:
    workDir: ~/angular-diff-match-patch
    steps:
      - type: checkout
      - type: shell
        name: Install Packages
        command: yarn install
      - type: shell
        name: Run Tests
        command: yarn test
      - type: test-results-store
        path: ./test/results
      - type: artifacts-store
        path: ./coverage
        destination: build
