version: 2
executorType: docker
containerInfo:
  - image: kkarczmarczyk/node-yarn:7.4
stages:
  build:
    workDir: ~/angular-diff-match-patch
    parallel: 4
    steps:
      - type: checkout
      - type: shell
        shell: /bin/bash
        command: yarn test
      - type: artifacts-store
      - type: test-results-store
