version: 2
executorType: docker
containerInfo:
  - image: kkarczmarczyk/node-yarn:7.4
stages:
  build:
    workDir: ~/angular-diff-match-patch
    environment:
      - CIRCLE_ARTIFACTS: /tmp/artifacts
      - CIRCLE_TEST_REPORTS: /tmp/test-results
    steps:
      - type: checkout
      - type: shell
        shell: /bin/bash
        command: yarn install
      - type: shell
        shell: /bin/bash
        command: yarn test
      - type: test-results-store
        path: ./test/results
      - type: artifacts-store
        path: ./coverage
        destination: build
