version: 2
executorType: docker
containerInfo:
  - image: kkarczmarczyk/node-yarn:7.4
stages:
  build:
    workDir: ~/angular-diff-match-patch
    environment:
      - CIRCLE_ARTIFACTS: /tmp/artifacts
      - CIRCLE_TEST_REPORTS: /tmp/test-results
    steps:
      - type: checkout
      - type: shell
        shell: /bin/bash
        command: yarn install
      - type: shell
        shell: /bin/bash
        command: |
          echo $CIRCLE_ARTIFACTS
          echo $CIRCLE_TEST_REPORTS
          mkdir $CIRCLE_ARTIFACTS
          mkdir $CIRCLE_TEST_REPORTS
        environment:
        - CIRCLE_ARTIFACTS: /tmp/artifacts
        - CIRCLE_TEST_REPORTS: /tmp/test-results
      - type: shell
        shell: /bin/bash
        command: |
          echo $CIRCLE_ARTIFACTS
          echo $CIRCLE_TEST_REPORTS
          mkdir $CIRCLE_ARTIFACTS
          mkdir $CIRCLE_TEST_REPORTS
      - type: shell
        shell: /bin.bash
        command: yarn test
      - type: artifacts-store
        path: $CIRCLE_ARTIFACTS
        destination: build
      - type: test-results-store
        path: $CIRCLE_TEST_REPORTS