version: 2
executorType: docker
containerInfo:
  - image: kkarczmarczyk/node-yarn:latest
stages:
  build:
    workDir: ~/angular-diff-match-patch
    steps:
      - checkout
      - run:
        name: Install packages
        command: yarn install
      - run:
        name: Run tests
        command: yarn test
      - run:
        name: Submit coverage report
        command: bash <(curl -s https://codecov.io/bash) -r amweiss/angular-diff-match-patch
      - store_test_results:
        path: ./test/results
      - store_artifacts:
        path: ./coverage
        destination: build
